# Config for AntiBully

server_name: ServerName

server_ip: mc.serverip.com

swear_block: false
bully_block: true
swear_deny_message: AntiBully has blocked your message as you have said blocked UN
bully_deny_message: AntiBully has blocked your message as you have said a blocked word!

#They can bypass all blocks (Trusted staff only)
staff:
    - xBarkPuppy1
    - StaffMember2
    - StaffMember3    

#Permenently mutes a player until they are removed (Perm ban mute)
bully_muted:
    - Bully1
    - Bully2
    - Bully3

#Blocked words
blocked_words:
    - Nigga 
    - Nigger
